<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangObatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            "Aciclovir 50 mg (@ 5 gram)",
            "Aciclovir 400 mg",
            "Alkohol 70%",
            "Chlorphenamine Maleate 4 mg",
            "Allopurinol 300 mg",
            "Tiap 5 mL mengandung : Ambroxol HCl 15 mg, Alkohol 0,7 % (Botol 60 mL)",
            "Ambroxol HCl 30 mg",
            "Amlodipin Besilate 5 mg",
            "Amlodipin Besilate 10 mg",
            "Medroxyprogesterone Acetate 150 mg/mL (Vial @1 mL)",
            "Ethinyl Estradiol 0,03 mg, Levonorgestrel 0,15 mg",
            "Asam Mefenamat 500 mg",
            "Acetylsalicylic Acid 100 mg",
            "Vitamin B1 100 mg, Vitamin B6 200 mg, Vitamin B12 200 mcg",
            "Bethamethasone Valerate 1 mg (@ 5 gram )",
            "Tiap gram mengandung : Placenta Extract 10 %, Neomycin Sulfate 0,5 % (Tube @ 15 gram)",
            "Metamizole Sodium 500 mg, Vitamin B1 50 mg, Vitamin B6 100 mg, Vitamin B12 100 mcg",
            "Tiap 5 mL mengandung : Paracetamol 120 mg, Guaifenesin 100 mg, Phenylephrine 2,5 mg (Botol 60 mL)",
            "Bromhexine HCl 8 mg",
            "Calcium Lactate 500 mg",
            "Candesartan Cilexetil 16 mg",
            "Captopril 12,5 mg",
            "MULTIVITAMIN",
            "Cefadroxil Monohydrate 500 mg",
            "Tiap 5 mL mengandung : Cefixim 100 mg (Botol 30 mL)",
            "Cefixime Trihydrate 200 mg",
            "Ceftriaxon Sodium 1 gram",
            "Tiap 5 mL mengandung : Cetirizin HCl 5 mg (Botol 60 mL)",
            "Cetirizine HCl 10 mg",
            "Chlorphenamine Maleate 4 mg",
            "Ciprofloxacin HCl 500 mg",
            "Clindamycin 300 mg",
            "Tiap Unit Dosis Mengandung : Ipratropium Bromide 0,5 mg, Salbutamol Sulfate 2,5 mg (Vial @2,5 mL)",
            "Tiap 5 mL mengandung : Paracetamol 120 mg, Guaifenesin 50 mg, Pseudoephedrine HCl 7,5 mg, Chlorphenamine Maleate 0,5 mg, Etanol 96 % 1,6 %v/v (Botol 60 mL)",
            "Sulfamethoxazole 800 mg, Trimethoprim 160 mg",
            "Tiap 5 mL mengandung : Sulfamethoxazole 200 mg, Trimethoprim 40 mg (Botol 60 mL)",
            "Dexamethasone 0,5 mg",
            "Tiap 5 mL mengandung : Paracetamol 120 mg (Botol 60 mL)",
            "Tiap mL mengandung : Dexamethasone Sodium Phosphate 5 mg / mL, Ampul @1 mL",
            "Dexchlorpheniramine Maleate 2 mg, Dexamethasone 05 mg",
            "Setiap 500 mL larutan mengandung : Dextrose Anhydrate 25.00 gram, Water for Injection Ad 500 mL",
            "Diclofenac Sodium 25 mg",
            "Digoxin 0,25 mg",
            "Tiap 5 mL mengandung : Thiamphenicol 125 mg (Botol 60 mL)",
            "Thiamphenicol 500 mg",
            "Doxycycline Hyclate 100 mg",
            "Tiap 5 mL mengandung : Domperidone 5 mg (Botol 60 mL)",
            "Metoclopramide HCl 10 mg",
            "Paracetamol 500 mg",
            "Eperison HCl 50 mg",
            "Tiap 0,6 mL mengandung : Paracetamol 60 mg (100 mg / mL) (Botol 15 mL)",
            "Chloramphenicol 1 % (@10 mL)",
            "Diclofenac Potassium 50 mg",
            "Ketorolac Trometamol 10 mg",
            "Isosorbide Dinitrate 5 mg",
            "Paracetamol 500 mg, Guaifenesin 50 mg, Phenylpropanolamine HCl 15 mg, Dextromethorphan HBr 15 mg, Chlorphenamine Maleate 1 mg",
            "Flunarizine HCl 5 mg",
            "Paracetamol 500 mg, Phenylpropanolamine HCl 15 mg, Chlorphenamine Maleate 2 mg, Guaifenesin 50 mg",
            "Folic Acid 400 mcg",
            "Folic Acid 400 mcg",
            "Furosemid 40 mg",
            "Gabapentin 300 mg",
            "Gemfibrozil 300 mg",
            "Gentamicin Sulfate 1 mg (@ 15 gram)",
            "Gentamicin Sulfate 3 mg / 0,3 % (@5 mL)",
            "Glibenclamide 5 mg",
            "Glimepirid 2 mg",
            "Metronidazole 500 mg",
            "Dextromethorpan HBr 15 mg, Guaifenesin 100 mg, Diphenhydramine HCl 5 mg",
            "Heparin Sodium 200 IU/gram (@ 15 gram)",
            "Betahistine Mesilate 6 mg",
            "Ranitidine HCl 150 mg",
            "Tiap 5 mL mengandung : Domperidone 5 mg (Botol 60 mL)",
            "Tiap 5 mL mengandung : Aluminium Hydroxide 200 mg, Magnesium Hydroxide 200 mg, Simethicone 50 mg (Botol 60 mL)",
            "Aluminium Hydroxide 200 mg, Magnesium Hydroxide 200 mg, Simethicone 50 mg",
            "Tiap 5 mL mengandung : Amoxicillin 125 mg (Botol 60 mL)",
            "Amoxicillin Trihydrate 500 mg",
            "Tiap 5 mL mengandung : Ibuprofen 100 mg (Botol 60 mL)",
            "Ibuprofen 400 mg",
            "Dexamethasone 0,5 mg",
            "Loperamide HCl 2 mg",
            "Mebhydroline Napadisylate 50 mg",
            "Tiap 5 mL mengandung : Paracetamol 120 mg (Botol 60 mL)",
            "Tiap 5 mL mengandung : Paracetamol 120 mg (Botol 60 mL)",
            "Tiap 5 mL mengandung : Kaolin 985 mg, Pectin 22 mg (Botol 60 mL)",
            "Ketoconazole 20 mg (@ 10 gram)",
            "Ketoconazole 200 mg",
            "Tiap mL mengandung : Ketorolac Trometamol 30 mg / mL, Ampul @1 mL",
            "Lansoprazole 30 mg",
            "Loratadine 10 mg",
            "Tiap 5 mL mengandung : Cefadroxil 125 mg (Botol 60 mL)",
            "Tiap 5 mL mengandung : Cefadroxil 250 mg (Botol 60 mL)",
            "Mecobalamin 500 mcg",
            "Meloxicam 15 mg",
            "Meloxicam 7,5 mg",
            "Tiap 3 mL mengandung : Vitamin B1 (Thiamine HCl) 100 mg, Vitamin B6 (Pyridoxine HCl) 100 mg, Vitamin B12 (Cyanocobalamin) 5000 mcg, Ampul @3 Ml",
            "Metformin 500 mg",
            "Methyl Prednisolone 4 mg",
            "Tiap 5 mL mengandung : Paracetamol 120 mg, Alkohol 96 % 1,6 %v/v (Botol 60 mL)",
            "Tiap mL mengandung : Metamizole Sodium Monohydrate 500 mg / mL, Ampul @2 Ml",
            "Tiap 15 mL mengandung : Succus Liquiritiae 500 mg, Ammonium Chloride 300 mg (Botol 100 mL)",
            "Domperidone 10 mg",
            "Omeprazole 20 mg",
            "Omeprazole Sodium Monohydrate 40 mg",
            "Tiap mL mengandung : Ondansetron HCl Dihydrate 2 mg / mL, Ampul @2 Ml",
            "Ondansetron HCl Dihydrate 4 mg",
            "Tiap 5 mL mengandung : Paracetamol 120 mg, Guaifenesin 50 mg, Chlorphenamine Maleate 1 mg, Ethanol 7,5 % v/v (Botol 60 mL)",
            "Tiap 5 mL mengandung : Paracetamol 120 mg, Guaifenesin 50 mg, Chlorphenamine Maleate 1 mg, Ethanol 7,5 % v/v (Botol 60 mL)",
            "Tiap Suppositoria mengandung : Paracetamol 125 mg",
            "Tiap 100 mL mengandung : Paracetamol 1 gram (Botol 100 mL)",
            "Paracetamol 500 mg, Phenylpropanolamine HCl 15 mg, Chlorphenamine Maleate 2 mg, Dextromethorphan HBr 15 mg",
            "Tiap mL mengandung : Lidocain HCl 20 mg, Epinephrine 0,0125 mg, Ampul @2mL",
            "Povidone Iodine",
            "Tiap mL mengandung : Ranitidin 25 mg / mL, Ampul @2 mL",
            "Rifampicin 450 mg",
            "Setiap 500 mL larutan mengandung : Calcium Chloride 2H2O 0,10 g, Potassium Chloride 0,15 g, Sodium Chloride 3,00 g, Sodium 130 mEq/L, Potassium 4 mEq/L, Calcium 2,7 mEq/L, Sodium Lactate 1,55 g, Air untuk Injeksi sampai 500 mL",
            "Salbutamol Sulfate 4 mg",
            "MULTIVITAMIN",
            "MULTIVITAMIN",
            "Simvastatin 20 mg",
            "Setiap 500 mL larutan mengandung : Sodium Chloride 4,5 g, Water for Injection Ad 500 mL, Sodium 154 mEq/L, Chloride 154 mEq/L",
            "Paracetamol 500 mg, Hyoscine-N-Butylbromide 10 mg",
            "Tiap 5 mL mengandung : Sucralfate 500 mg (Botol 100 mL)",
            "Tiap Suppositoria mengandung : Benzocaine 23 mg, Zinc Oxide 46 mg, Aluminium Hydroxide 5,75 mg",
            "Ferrous Fumarate (FE) 60 mg, Folic Acid 0,4 mg",
            "Salbutamol Sulfate 1,2 mg, Theophylline 130 mg",
            "Asam Tranexamat 500 mg",
            "Paracetamol 500 mg",
            "Vitamin A 2000 IU",
            "Vitamin B1 2 mg, Vitamin B2 2 mg, Vitamin B6 HCl 2 mg, Nicotinamid 20 mg, Calcium Pantothenate 10 mg",
            "Vitamin B6 HCl 10 mg",
            "Ascorbic Acid 50 mg",
            "Vitamin D3 1000 IU",
            "Tiap 5 mL mengandung : Amoxicillin 125 mg (Botol 60 mL)",
            "Amoxicillin Trihydrate 500 mg",
            "Tiap gram mengandung : Betamethasone 1 mg, Gentamicin 1 mg (Tube @ 10 gram)",
            "Tiap 5 mL mengandung : Zinc Sulfate Monohydrate 20 mg (Botol 60 mL)",
            "Zinc Sulfate Monohydrate 20 mg"
        ];

        $dataToInsert = [];
        $now = now();

        foreach ($items as $index => $namaBarang) {
            $dataToInsert[] = [
                'kode_barang'  => 'B' . str_pad($index + 1, 6, '0', STR_PAD_LEFT),
                'nama_barang'  => $namaBarang,
                'stok_global'  => 1000,
                'isi_konversi' => 1,
                'created_at'   => $now,
                'updated_at'   => $now,
            ];
        }

        // Chunk insert per 100 data
        foreach (array_chunk($dataToInsert, 100) as $chunk) {
            DB::table('mt_barang')->insert($chunk);
        }
    }
}