<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        $items = [
            "Paracetamol Tab 500mg btl IFI",
            "Nutradon Tab 500mg btl",
            "Ibuprofen Tab 400mg TRIMAN",
            "Metamizole Tab 500mg btl IFI/META",
            "Zelona tab 50mg",
            "Asam Mefenamat Tab 500mg ETA",
            "Meloxicam Tab 15mg TROPICA",
            "Amoxicillin tab 500mg HEXA",
            "Ciprofloxacin tab 500mg BERNO",
            "Metronidazole tab 500mg NUFA",
            "Clindamycin tab 300mg DEXA",
            "Dohixat tab 100mg",
            "Cefixime tab 200mg Dexa",
            "Cotrimoksazole tab 400mg MERSI",
            "Cefadroxil tab 500mg INFION",
            "Ranitidine tab 150mg HEXA",
            "Antasida doen tab btl TRIMAN",
            "Antasida doen tab btl MUTIFA",
            "Lanzoprazole tab 30mg NUFARINDO",
            "Norvom tab 10mg (Metoclorpamid)",
            "Sucralfate syr 100ml MEPRO",
            "Sucralfate syr 100ml DEXA",
            "Domperidone 10mg tab ERLIMPEX",
            "Elsiron tab",
            "Ambroxol tab 30mg TRIMAN",
            "Coredryl Syr",
            "Grantusif tab",
            "Bromhexine tab 8mg ERLIMPEX",
            "Guaifenesin tab 100mg btl CITO/TRIFA",
            "IFIDEX (Dexamethason) 0,5mg tab btl",
            "Methylprednisolone tab 4mg INFION/DEXA",
            "CTM 4mg tab btl META",
            "Cetirizine 10mg tab MEGA",
            "Amlodipine 10mg tab NUFA",
            "Amlodipine 10mg tab Mutifa",
            "Captopril 25mg tab ETA",
            "Propanolol 10mg tab DEXA",
            "Bisoprolol 5mg tab NOVELL",
            "Candesartan 8mg tab DEXA",
            "Glibenclamide 5mg tab INFION",
            "Metformin 500mg tab DEXA",
            "Glimepiride tab 4 mg DEXA",
            "Vitamin B Complex tab btl MEF",
            "Cavicur tab",
            "Anelat 1000mcg tab",
            "Etabion tab",
            "Novakalk 500mg tab",
            "Acyclovir 400mg tab PHAPROS",
            "Simvastatin 20mg tab QUANTUM",
            "Simvastatin 10mg tab MULIA",
            "Allopurinol 100mg tab Triman",
            "Allopurinol 300mg tab BERNO",
            "Spironolactone 25mg tab DEXA",
            "Furosemide 40mg tab FM",
            "Ketoconazole 200mg tab HEXA",
            "Asam Tranexamat 500mg tab",
            "Clopidogrel 75mg tab NOVEL",
            "Aspilet 80mg tab",
            "Isosorbide Dinitrat 5mg tab YARI",
            "Bisacodyl 5mg tab",
            "Supperhoid supp",
            "Antihemorroid supp",
            "Antihemorroid supp KF",
            "Salbutamol 4mg tab Yarindo",
            "Salbutamol 4mg tab MULIA",
            "Salbutamol 4mg tab INF",
            "Histigen tab 6mg",
            "Dimenhydrinate tab 50mg KF",
            "Relaxon tab",
            "Scopma Plus tab",
            "Puralex tab 630mg",
            "Yusimox syr",
            "Flutop syr",
            "Kanina syr",
            "Vesperum syr",
            "Procurma syr",
            "Nisagon cream 5G",
            "Betamethason cream 5G Berno",
            "Salgen Cream 15G",
            "Gentamicin cream FM",
            "Acyclovir cream FM",
            "Permetrin cream 15gr",
            "Scabimite cream 10gr",
            "Scabimite cream 30gr",
            "Ketoconazole cream Mulia 10 gr",
            "Erla SM",
            "Reco SM",
            "GOM",
            "Pipet",
            "Reco TM",
            "Erla TT",
            "Rifampisin 450mg",
            "Isoniazid",
            "Pyrazinamid",
            "Etambutol",
            "Ketorolac amp 30mg/1 ml mepro",
            "Ranitidine amp 50 mg/2 ml mepro",
            "Ondancetron amp 4mg/2 ml IPHA/Soho",
            "Dexamethason amp 5mg/1 ml mepro",
            "Lidocain amp 40mg/2 ml IPHA",
            "Meprovent 2.5 ml",
            "Ceftriaxone 1 gr vial interbit",
            "Paracetamol infus 1000mg/10 ml mersi",
            "Cyclofem vial",
            "Tricloflem vial",
            "Metamidon vial/10ml, 500mg/ml",
            "Recodryl vial/15 ml",
            "Neurotropic vial/9 ml",
            "NS 0.9% 500cc mjb/satoria",
            "RL 500cc mjb",
            "Dextrose 10% 500cc",
            "Dextrose 40% Otsuka",
            "Alprazolam 0.5mg",
            "Diazepam 5mg/amp",
            "Spuit 1cc onemed",
            "Spuit 3cc onemed",
            "Spuit 5cc onemed",
            "Spuit 10cc onemed",
            "Spuit 20cc onemed",
            "Needle 26G",
            "Infus Set Macro Onemed",
            "Infus Set Macro OneHealth",
            "Infus Set Micro Onemed",
            "Infus Set Micro Onehealth",
            "Abocath 20G onehealth",
            "Abocath 20G inflo",
            "Abocath 22G onehealth",
            "Abocath 22G inflo",
            "Abocath 24G onehealth",
            "Abocath 24G inflo",
            "Neddle 26G onemed",
            "Suture Needle GT Sutura/Remidi no 12",
            "Suture Needle GT Sutura/Remidi no 10",
            "Suture Needle GT Sutura/Remidi no 8",
            "Suture Needle GT Sutura/Remidi no 6",
            "Plain catgut 3.0 GEA",
            "Chromic catgut 3.0 GEA",
            "Kassa Steril 200pcs",
            "Plesterin 200pcs",
            "Ultrafix 10cmx5m",
            "Chili Plast Roll 1.25cm x 4.5m isi 12pcs",
            "Micropore 1.25cm x 9.1m isi 12 pcs",
            "Diluent",
            "Probe Clenser",
            "Tabung Darah isi 100",
            "HIV Kit isi 25",
            "HbSAg isi 50",
            "Widal (cairan)"
        ];

        $dataToInsert = [];

        foreach ($items as $index => $namaBarang) {
            $kodeBarang = 'B' . str_pad($index + 1, 6, '0', STR_PAD_LEFT);

            $dataToInsert[] = [
                'kode_barang'   => $kodeBarang,
                'nama_barang'   => $namaBarang,
                'nama_generik'  => '-',
                'nama_pabrik'   => '-',
                'jenis_barang'  => 'obat',
                'kategori_obat' => 'bebas',
                'bentuk_sediaan'=> '-',
                'satuan_besar'  => '-',
                'satuan_sedang' => '-',
                'satuan_kecil'  => '-',
                'stok_global'   => 0,
                'isi_konversi'  => 1,
                'aturan_pakai'  => '-',
                'harga_jual'    => '-',
                'created_at'    => $now,
                'updated_at'    => $now,
            ];
        }

        DB::table('mt_barang')->insert($dataToInsert);
    }
}