<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MtBarangNpMedikaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'nama_barang' => 'Paracetamol Tab 500mg btl IFI',
                'harga_normal' => 1750,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'PCT',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Paracetamol (Nutradon) Tab 500mg btl',
                'harga_normal' => 1800,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'NTD',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Ibuprofen Tab 400mg TRIMAN',
                'harga_normal' => 2400,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'IFN',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Metamizole Tab 500mg btl IFI/META',
                'harga_normal' => 2100,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'MTM',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Zelona tab 50mg',
                'harga_normal' => 2851,
                'harga_tebus' => 10000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'NDC',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Asam Mefenamat Tab 500mg ETA',
                'harga_normal' => 2200,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3X1 PC',
                'nama_display' => 'ASM',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Meloxicam Tab 15mg TROPICA',
                'harga_normal' => 2900,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2X1 PC',
                'nama_display' => 'MLX',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Amoxicillin tab 500mg HEXA',
                'harga_normal' => 4600,
                'harga_tebus' => 15000,
                'aturan_pakai' => '3X1 PC',
                'nama_display' => 'AMX',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Ciprofloxacin tab 500mg BERNO',
                'harga_normal' => 5000,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2X1 PC',
                'nama_display' => 'CPR',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Metronidazole tab 500mg NUFA',
                'harga_normal' => 2100,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 OC',
                'nama_display' => 'MTZ',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Clindamycin tab 300mg DEXA',
                'harga_normal' => 7600,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2X1 PC',
                'nama_display' => 'CLN',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Doksisiklin (Dohixat) tab 100mg',
                'harga_normal' => 3850,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2X1 PC',
                'nama_display' => 'DHT',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Cefixime tab 200mg Dexa',
                'harga_normal' => 14000,
                'harga_tebus' => 20000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'CFM',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Cotrimoksazole tab 400mg MERSI',
                'harga_normal' => 2200,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'CTR',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Cefadroxil tab 500mg INFION',
                'harga_normal' => 6500,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'CFD',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],

            // PPI dan Anti Emetik
            [
                'nama_barang' => 'Ranitidine tab 150mg HEXA',
                'harga_normal' => 1850,
                'harga_tebus' => 10000,
                'aturan_pakai' => '2x1 AC 30m',
                'nama_display' => 'RTD',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Antasida doen tab btl TRIMAN',
                'harga_normal' => 900,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 AC 30m',
                'nama_display' => 'DXA',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Antasida doen tab btl MUTIFA',
                'harga_normal' => 951,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 AC 30m',
                'nama_display' => 'DXA',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Lanzoprazole tab 30mg NUFARINDO',
                'harga_normal' => 6251,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2x1 AC 30m',
                'nama_display' => 'LNS',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Norvom tab 10mg (Metoclorpamid)',
                'harga_normal' => 1550,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 AC 30m',
                'nama_display' => 'EMRN',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Sucralfate syr 100ml MEPRO',
                'harga_normal' => 10000,
                'harga_tebus' => 20000,
                'aturan_pakai' => '3x1 AC 30m',
                'nama_display' => 'SCR',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Sucralfate syr 100ml DEXA',
                'harga_normal' => 12001,
                'harga_tebus' => 20000,
                'aturan_pakai' => '3x1 AC 30m',
                'nama_display' => 'SCR',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Domperidone 10mg tab ERLIMPEX',
                'harga_normal' => 1750,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 AC 30m',
                'nama_display' => 'DMD',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Batuk
            [
                'nama_barang' => 'Elsiron tab',
                'harga_normal' => 5300,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'ESN',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Ambroxol tab 30mg TRIMAN',
                'harga_normal' => 1100,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'ABRL',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Coredryl Syr',
                'harga_normal' => 7800,
                'harga_tebus' => 15000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'CRD',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Grantusif tab',
                'harga_normal' => 3750,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'GRT',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Bromhexine tab 8mg ERLIMPEX',
                'harga_normal' => 750,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'BMX',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Guaifenesin tab 100mg btl CITO/TRIFA',
                'harga_normal' => 900,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'GG',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Kortikosteroid
            [
                'nama_barang' => 'Dexamethason (IFIDEX) 0,5mg tab btl',
                'harga_normal' => 560,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'DMT',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Methylprednisolone tab 4mg INFION/DEXA',
                'harga_normal' => 1800,
                'harga_tebus' => 10000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'MP',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Anti Histamin
            [
                'nama_barang' => 'CTM 4mg tab btl META',
                'harga_normal' => 366,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'CTM',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Cetirizine 10mg tab MEGA',
                'harga_normal' => 1101,
                'harga_tebus' => 10000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'CTZ',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Anti Hipertensi
            [
                'nama_barang' => 'Amlodipine 10mg tab NUFA',
                'harga_normal' => 1500,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'AML',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Amlodipine 10mg tab Mutifa',
                'harga_normal' => 2700,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'AML',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Captopril 25mg tab ETA',
                'harga_normal' => 900,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'CPT',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Propanolol 10mg tab DEXA',
                'harga_normal' => 1500,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'PRP',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Bisoprolol 5mg tab NOVELL',
                'harga_normal' => 7000,
                'harga_tebus' => 15000,
                'aturan_pakai' => null,
                'nama_display' => 'BSP',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Candesartan 8mg tab DEXA',
                'harga_normal' => 7667,
                'harga_tebus' => 15000,
                'aturan_pakai' => null,
                'nama_display' => 'CDS',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],

            // Anti Diabetik
            [
                'nama_barang' => 'Glibenclamide 5mg tab INFION',
                'harga_normal' => 1530,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'GLB',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Metformin 500mg tab DEXA',
                'harga_normal' => 1875,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'MTF',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Glimepiride tab 4 mg DEXA',
                'harga_normal' => 6000,
                'harga_tebus' => 15000,
                'aturan_pakai' => null,
                'nama_display' => 'GLM',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],

            // Vitamin
            [
                'nama_barang' => 'Vitamin B Complex tab btl MEF',
                'harga_normal' => 1100,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'VTB',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Cavicur tab',
                'harga_normal' => 5650,
                'harga_tebus' => 15000,
                'aturan_pakai' => null,
                'nama_display' => 'CVC',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Anelat 1000mcg tab',
                'harga_normal' => 1400,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'ANL',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Etabion tab',
                'harga_normal' => 2150,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'ETB',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Novakalk 500mg tab',
                'harga_normal' => 1400,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'NVK',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Anti Viral
            [
                'nama_barang' => 'Acyclovir 400mg tab PHAPROS',
                'harga_normal' => 5000,
                'harga_tebus' => 15000,
                'aturan_pakai' => null,
                'nama_display' => 'ACL',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],

            // Statin
            [
                'nama_barang' => 'Simvastatin 20mg tab QUANTUM',
                'harga_normal' => 3000,
                'harga_tebus' => 10000,
                'aturan_pakai' => '1x1 pc malam',
                'nama_display' => 'SVT2',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Simvastatin 10mg tab MULIA',
                'harga_normal' => 2000,
                'harga_tebus' => 10000,
                'aturan_pakai' => '1x1 PC malam',
                'nama_display' => 'SVT1',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Gout
            [
                'nama_barang' => 'Allopurinol 100mg tab Triman',
                'harga_normal' => 1660,
                'harga_tebus' => 10000,
                'aturan_pakai' => '1x1 PC malam',
                'nama_display' => 'ALP1',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Allopurinol 300mg tab BERNO',
                'harga_normal' => 4550,
                'harga_tebus' => 15000,
                'aturan_pakai' => '1x1 PC malam',
                'nama_display' => 'ALP3',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],

            // Diuretik
            [
                'nama_barang' => 'Spironolactone 25mg tab DEXA',
                'harga_normal' => 3500,
                'harga_tebus' => 15000,
                'aturan_pakai' => null,
                'nama_display' => 'SPN',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Furosemide 40mg tab FM',
                'harga_normal' => 1500,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'FSD',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Anti Jamur
            [
                'nama_barang' => 'Ketoconazole 200mg tab HEXA',
                'harga_normal' => 3850,
                'harga_tebus' => 10000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'KTZ',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Anti Perdarahan
            [
                'nama_barang' => 'Asam Tranexamat 500mg tab',
                'harga_normal' => 10000,
                'harga_tebus' => 20000,
                'aturan_pakai' => '3x1 PC prn',
                'nama_display' => 'AST',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],

            // Antiplatelet
            [
                'nama_barang' => 'Clopidogrel 75mg tab NOVEL',
                'harga_normal' => 18334,
                'harga_tebus' => 25000,
                'aturan_pakai' => '1x1 PC',
                'nama_display' => 'CPG',
                'golongan_obat' => 'D',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Aspilet 80mg tab',
                'harga_normal' => 6161,
                'harga_tebus' => 15000,
                'aturan_pakai' => '1x1 PC',
                'nama_display' => 'ASP',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],

            // Anti Angina
            [
                'nama_barang' => 'Isosorbide Dinitrat 5mg tab YARI',
                'harga_normal' => 1200,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'ISDN',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Konstipasi
            [
                'nama_barang' => 'Bisacodyl 5mg tab',
                'harga_normal' => 5550,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'BSD',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],

            // Anti Hemorroids
            [
                'nama_barang' => 'Supperhoid supp',
                'harga_normal' => 4667,
                'harga_tebus' => 15000,
                'aturan_pakai' => '1x1 malam',
                'nama_display' => 'SPH',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Antihemorroid supp',
                'harga_normal' => 3259,
                'harga_tebus' => 15000,
                'aturan_pakai' => '1x1 malam',
                'nama_display' => 'AHD',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Antihemorroid supp KF',
                'harga_normal' => 3630,
                'harga_tebus' => 15000,
                'aturan_pakai' => '1x1 malam',
                'nama_display' => 'AHD',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],

            // Bronkodilator
            [
                'nama_barang' => 'Salbutamol 4mg tab Yarindo',
                'harga_normal' => 980,
                'harga_tebus' => 10000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'SBT4',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Salbutamol 4mg tab MULIA',
                'harga_normal' => 1551,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'SBT4',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Salbutamol 4mg tab INF',
                'harga_normal' => 974,
                'harga_tebus' => 10000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'SBT4',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Anti Vertigo
            [
                'nama_barang' => 'Histigen tab 6mg',
                'harga_normal' => 4200,
                'harga_tebus' => 15000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'BTA',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Flunarizin (Vertilon) 5mg',
                'harga_normal' => 5000,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2x1 PC',
                'nama_display' => 'FNZ',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Dimenhydrinate tab 50mg KF',
                'harga_normal' => 1450,
                'harga_tebus' => 10000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'DMH',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Anti Spasmodik
            [
                'nama_barang' => 'Relaxon tab',
                'harga_normal' => 6500,
                'harga_tebus' => 15000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'EPS',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Scopma Plus tab',
                'harga_normal' => 11050,
                'harga_tebus' => 20000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'SCP',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],

            // Diare
            [
                'nama_barang' => 'Puralex tab 630mg',
                'harga_normal' => 0,
                'harga_tebus' => 10000,
                'aturan_pakai' => null,
                'nama_display' => 'PRX',
                'golongan_obat' => 'A',
                'stok' => 10000,
            ],

            // Sirup
            [
                'nama_barang' => 'Yusimox syr',
                'harga_normal' => 5600,
                'harga_tebus' => 25000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'RACIKAN < 10 KG',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Flutop syr',
                'harga_normal' => 8800,
                'harga_tebus' => 15000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'FTP',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Etagesic syr',
                'harga_normal' => 6200,
                'harga_tebus' => 15000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'EGC',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Kanina syr',
                'harga_normal' => 5401,
                'harga_tebus' => 15000,
                'aturan_pakai' => null,
                'nama_display' => 'KNN',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Vesperum syr',
                'harga_normal' => 5600,
                'harga_tebus' => 15000,
                'aturan_pakai' => '3x1 AC',
                'nama_display' => 'VSP',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Procurma syr',
                'harga_normal' => 5400,
                'harga_tebus' => 15000,
                'aturan_pakai' => '3x1 PC',
                'nama_display' => 'PCR',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],

            // Salep
            [
                'nama_barang' => 'Nisagon cream 5G',
                'harga_normal' => 6400,
                'harga_tebus' => 20000,
                'aturan_pakai' => '2x1',
                'nama_display' => 'NSG',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Betamethason cream 5G Berno',
                'harga_normal' => 2600,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2x1',
                'nama_display' => 'BTM',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Salgen Cream 15G',
                'harga_normal' => 6800,
                'harga_tebus' => 20000,
                'aturan_pakai' => '2x1',
                'nama_display' => 'SLG',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Gentamicin cream FM',
                'harga_normal' => 3300,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2x1',
                'nama_display' => 'GTM',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Acyclovir cream FM',
                'harga_normal' => 3200,
                'harga_tebus' => 15000,
                'aturan_pakai' => '3x1',
                'nama_display' => 'ACLS',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Permetrin cream 15gr',
                'harga_normal' => 27750,
                'harga_tebus' => 25000,
                'aturan_pakai' => '1x1 malam',
                'nama_display' => 'PMT',
                'golongan_obat' => 'D',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Scabimite cream 10gr',
                'harga_normal' => 44000,
                'harga_tebus' => 0,
                'aturan_pakai' => null,
                'nama_display' => 'SCB1',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Scabimite cream 30gr',
                'harga_normal' => 73000,
                'harga_tebus' => 0,
                'aturan_pakai' => null,
                'nama_display' => 'SCB3',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Ketoconazole cream Mulia 10 gr',
                'harga_normal' => 3500,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2x1',
                'nama_display' => 'KTZS',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Erla SM',
                'harga_normal' => 7700,
                'harga_tebus' => 20000,
                'aturan_pakai' => '2x1',
                'nama_display' => 'ELM',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Reco SM',
                'harga_normal' => 6000,
                'harga_tebus' => 20000,
                'aturan_pakai' => '2x1',
                'nama_display' => 'RSM',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'GOM',
                'harga_normal' => 3000,
                'harga_tebus' => 15000,
                'aturan_pakai' => '2x1',
                'nama_display' => 'GOM',
                'golongan_obat' => 'B',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Pipet',
                'harga_normal' => 2200,
                'harga_tebus' => 5000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => 'Z',
                'stok' => 10000,
            ],

            // Tetes
            [
                'nama_barang' => 'Reco TM',
                'harga_normal' => 8000,
                'harga_tebus' => 20000,
                'aturan_pakai' => '2x1',
                'nama_display' => 'RTM',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Erla TT',
                'harga_normal' => 10601,
                'harga_tebus' => 20000,
                'aturan_pakai' => '2x1',
                'nama_display' => 'ERM',
                'golongan_obat' => 'C',
                'stok' => 10000,
            ],

            // OAT
            [
                'nama_barang' => 'Rifampisin 450mg',
                'harga_normal' => 52000,
                'harga_tebus' => 72800,
                'aturan_pakai' => null,
                'nama_display' => 'R',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Isoniazid',
                'harga_normal' => 4100,
                'harga_tebus' => 5740,
                'aturan_pakai' => null,
                'nama_display' => 'H',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Pyrazinamid',
                'harga_normal' => 4500,
                'harga_tebus' => 6300,
                'aturan_pakai' => null,
                'nama_display' => 'Z',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Etambutol',
                'harga_normal' => 13500,
                'harga_tebus' => 18900,
                'aturan_pakai' => null,
                'nama_display' => 'E',
                'golongan_obat' => null,
                'stok' => 10000,
            ],

            // Injeksi
            [
                'nama_barang' => 'Ketorolac amp 30mg/1 ml mepro',
                'harga_normal' => 1321,
                'harga_tebus' => 1981,
                'aturan_pakai' => null,
                'nama_display' => 'K inj',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Ranitidine amp 50 mg/2 ml mepro',
                'harga_normal' => 1415,
                'harga_tebus' => 3080,
                'aturan_pakai' => null,
                'nama_display' => 'R Inj',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Ondancetron amp 4mg/2 ml IPHA/Soho',
                'harga_normal' => 2200,
                'harga_tebus' => 5837,
                'aturan_pakai' => null,
                'nama_display' => 'O Inj',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Dexamethason amp 5mg/1 ml mepro',
                'harga_normal' => 4169,
                'harga_tebus' => 2030,
                'aturan_pakai' => null,
                'nama_display' => 'D Inj',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Lidocain amp 40mg/2 ml IPHA',
                'harga_normal' => 1450,
                'harga_tebus' => 1981,
                'aturan_pakai' => null,
                'nama_display' => 'L Inj',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Meprovent 2.5 ml',
                'harga_normal' => 3663,
                'harga_tebus' => 3080,
                'aturan_pakai' => null,
                'nama_display' => 'M Nebu',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Ceftriaxone 1 gr vial interbit',
                'harga_normal' => 6500,
                'harga_tebus' => 9100,
                'aturan_pakai' => null,
                'nama_display' => 'C Inj',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Paracetamol infus 1000mg/10 ml mersi',
                'harga_normal' => 16000,
                'harga_tebus' => 22400,
                'aturan_pakai' => null,
                'nama_display' => 'P Inf',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Cyclofem vial',
                'harga_normal' => 9150,
                'harga_tebus' => 12810,
                'aturan_pakai' => null,
                'nama_display' => 'KB1',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Tricloflem vial',
                'harga_normal' => 8250,
                'harga_tebus' => 11550,
                'aturan_pakai' => null,
                'nama_display' => 'KB3',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Metamidon vial/10ml, 500mg/ml',
                'harga_normal' => 14500,
                'harga_tebus' => 14500,
                'aturan_pakai' => null,
                'nama_display' => 'M Inj',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Recodryl vial/15 ml',
                'harga_normal' => 5406,
                'harga_tebus' => 7569,
                'aturan_pakai' => null,
                'nama_display' => 'Reco Inj',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Neurotropic vial/9 ml',
                'harga_normal' => 9200,
                'harga_tebus' => 12880,
                'aturan_pakai' => null,
                'nama_display' => 'N Inj',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'NS 0.9% 500cc mjb/satoria',
                'harga_normal' => 7900,
                'harga_tebus' => 11060,
                'aturan_pakai' => null,
                'nama_display' => 'NS',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'RL 500cc mjb',
                'harga_normal' => 8500,
                'harga_tebus' => 11900,
                'aturan_pakai' => null,
                'nama_display' => 'RL',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Dextrose 10% 500cc',
                'harga_normal' => 0,
                'harga_tebus' => 0,
                'aturan_pakai' => null,
                'nama_display' => 'D10',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Dextrose 40% Otsuka',
                'harga_normal' => 11000,
                'harga_tebus' => 15400,
                'aturan_pakai' => null,
                'nama_display' => 'D40',
                'golongan_obat' => null,
                'stok' => 10000,
            ],

            // Narkotika & Alat Kesehatan
            [
                'nama_barang' => 'Alprazolam 0.5mg',
                'harga_normal' => 4400,
                'harga_tebus' => 6160,
                'aturan_pakai' => null,
                'nama_display' => 'Apz',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Diazepam 5mg/amp',
                'harga_normal' => 2997,
                'harga_tebus' => 4196,
                'aturan_pakai' => null,
                'nama_display' => 'Dzp',
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Spuit 1cc onemed',
                'harga_normal' => 700,
                'harga_tebus' => 980,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Spuit 3cc onemed',
                'harga_normal' => 700,
                'harga_tebus' => 980,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Spuit 5cc onemed',
                'harga_normal' => 700,
                'harga_tebus' => 980,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Spuit 10cc onemed',
                'harga_normal' => 1100,
                'harga_tebus' => 980,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Spuit 20cc onemed',
                'harga_normal' => 2000,
                'harga_tebus' => 2800,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Needle 26G',
                'harga_normal' => 1500,
                'harga_tebus' => 2100,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Infus Set Macro Onemed',
                'harga_normal' => 5000,
                'harga_tebus' => 7000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Infus Set Macro OneHealth',
                'harga_normal' => 5000,
                'harga_tebus' => 7000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Infus Set Micro Onemed',
                'harga_normal' => 5000,
                'harga_tebus' => 7000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Infus Set Micro Onehealth',
                'harga_normal' => 5000,
                'harga_tebus' => 7000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Abocath 20G onehealth',
                'harga_normal' => 4000,
                'harga_tebus' => 5600,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Abocath 20G inflo',
                'harga_normal' => 4000,
                'harga_tebus' => 5600,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Abocath 22G onehealth',
                'harga_normal' => 4000,
                'harga_tebus' => 5600,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Abocath 22G inflo',
                'harga_normal' => 4000,
                'harga_tebus' => 5600,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Abocath 24G onehealth',
                'harga_normal' => 5000,
                'harga_tebus' => 7000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Abocath 24G inflo',
                'harga_normal' => 5000,
                'harga_tebus' => 7000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Suture Needle GT Sutura/Remidi no 12',
                'harga_normal' => 2500,
                'harga_tebus' => 3500,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Suture Needle GT Sutura/Remidi no 10',
                'harga_normal' => 2500,
                'harga_tebus' => 3500,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Suture Needle GT Sutura/Remidi no 8',
                'harga_normal' => 2500,
                'harga_tebus' => 3500,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Suture Needle GT Sutura/Remidi no 6',
                'harga_normal' => 2500,
                'harga_tebus' => 3500,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Plain catgut 3.0 GEA',
                'harga_normal' => 2500,
                'harga_tebus' => 3500,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Chromic catgut 3.0 GEA',
                'harga_normal' => 2500,
                'harga_tebus' => 3500,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Kassa Steril 200pcs',
                'harga_normal' => 50000,
                'harga_tebus' => 70000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Plesterin 200pcs',
                'harga_normal' => 35000,
                'harga_tebus' => 49000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Ultrafix 10cmx5m',
                'harga_normal' => 30000,
                'harga_tebus' => 42000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Chili Plast Roll 1.25cm x 4.5m isi 12pcs',
                'harga_normal' => 150000,
                'harga_tebus' => 210000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Micropore 1.25cm x 9.1m isi 12 pcs',
                'harga_normal' => 30000,
                'harga_tebus' => 42000,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],

            // BHP Alat Lab
            [
                'nama_barang' => 'Diluent',
                'harga_normal' => 950000,
                'harga_tebus' => 0,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Probe Clenser',
                'harga_normal' => 0,
                'harga_tebus' => 0,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Tabung Darah isi 100',
                'harga_normal' => 0,
                'harga_tebus' => 0,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'HIV Kit isi 25',
                'harga_normal' => 0,
                'harga_tebus' => 0,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'HbSAg isi 50',
                'harga_normal' => 0,
                'harga_tebus' => 0,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
            [
                'nama_barang' => 'Widal (cairan)',
                'harga_normal' => 0,
                'harga_tebus' => 0,
                'aturan_pakai' => null,
                'nama_display' => null,
                'golongan_obat' => null,
                'stok' => 10000,
            ],
        ];
        DB::table('mt_barang_np_medika')->insert($data);
    }
}
